#define IDM_GAME_MENU      100
#define IDM_NEW            101
#define IDM_EXIT           102
#define IDM_SET_NAMES      103
#define IDM_OPTIONS        104

#define DID_STOFFSET       1000                          
#define DID_LEFT           100
#define DID_RIGHT          101
#define DID_CRICKET        102
#define DID_301            103
#define DID_START_SCORE    104
#define DID_START_DOUBLE   105

#define DID_OK             1
#define DID_CANCEL         2
